### ISSUE TITLE
Reported totals are slighty different compared to valgrind output

### ISSUE THREAD

**Issue by koivunej** [nnethercote/dhat-rs#1]
While trying this with a few trivial binaries I noticed the summaries are a bit different from what the valgrind-3.15.0 or valgrind-3.17.0.GIT report. The two valgrind versions agree on the totals, except on reads/writes. This is likely nothing critical and I am asking mostly out of interest, if you'd already know why the numbers are different.

dhat-rs 0.1.1:

```
dhat: Total:     44,792 bytes in 92 blocks
dhat: At t-gmax: 25,872 bytes in 9 blocks
dhat: At t-end:  9,344 bytes in 5 blocks
```

valgrind-3.17.0.GIT (on f4d98ff79d5a79102b777ea7e23002d9f7326489):

```
==79275== Total:     46,769 bytes in 101 blocks
==79275== At t-gmax: 25,957 bytes in 12 blocks
==79275== At t-end:  8,232 bytes in 2 blocks
==79275== Reads:     4,855,431 bytes
==79275== Writes:    921,275 bytes
```

I am mainly wondering about the difference in Total between `dhat-rs` and `valgrind --tool=dhat --mode=heap`. The above binary was a debug build. The optimized builds get the same respective totals.

**Comment by nnethercote** [comment]
It's a good observation. I have added an explanation to the docs.
