### ISSUE TITLE
Consider hosting a version of the viewer online

### ISSUE THREAD

**Issue by gregtatum** [nnethercote/dhat-rs#11]
It would be nice if this utility pointed to a hosted version online. It could be as simple as a `github.io` static page. It's a bit confusing trying to find the viewer after running the example code. It would be nice to be able to open a link logged after running the example.

**Comment by gregtatum** [comment]
I have one online here: https://gregtatum.github.io/dhat-viewer/dh_view.html

**Comment by nnethercote** [comment]
Thanks for the suggestion. Now [here](https://nnethercote.github.io/dh_view/dh_view.html), and the docs in 0.2.2. point to it.

**Comment by gregtatum** [comment]
Thanks!
