### ISSUE TITLE
What is the expected overhead?

### ISSUE THREAD

**Issue by Eh2406** [nnethercote/dhat-rs#16]
I am happily using this to make my code faster. Thank you!
The hardest part is making small enough examples to run in a handful of minutes. When I comment out the `let _dhat = Dhat::start_heap_profiling();` it takes less then one second. Is this intended?
If this level of overhead is exemptible, can we document it?
If not, I will try to build a reproducible example.

**Comment by nnethercote** [comment]
Hi, sorry for the much-delayed response here. I don't have a good sense of what the overhead should be, though I was hoping it would be less than 2x. So if you're going from less than one second to minutes, something is very wrong...

**Comment by Eh2406** [comment]
I still use and love this library! Thank you so much for it, and welcome back to the community!

There have been many improvements to my benchmark and program that reduce the overhead since I posted this. I thought I would start by measuring what it is up to now. The current version of the code is [here](https://github.com/pubgrub-rs/pubgrub/blob/dhat-rs/examples/dhat_large_case.rs), here is the timings of `cargo run --example dhat_large_case --features="serde"`, on my Win10 Ryzen 3950X Rust msvc v1.56.1.

code|debug|release
---|---|---
`// let _dhat`| 0.26s | 0.015s
`let _dhat`| 13.8s | 16.1s

So there is still a lot of overhead. I can try and profile or minimize the example if that would be helpful. Just let me know how I can help!

**Comment by nnethercote** [comment]
I just tried your example on my Linux desktop and my MacBook Pro. I see output like this:
```
large_case_u16_NumberVersion.ron
0.71654105
dhat: Total:     7,880,830 bytes in 26,131 blocks
dhat: At t-gmax: 74,672 bytes in 158 blocks
dhat: At t-end:  1,024 bytes in 1 blocks
dhat: The data in dhat-heap.json is viewable with dhat/dh_view.html
```
I assume the 0.71654105 is the number to report. Here's what I get when I go from normal to `dhat`-enabled:
- Linux
  - debug: 0.20s -> 0.71s
  - release: 0.01s -> 0.13s
- Mac
  - debug: 0.24s -> 0.61s
  - release: 0.01s -> 0.05s

The slowdown is definitely more than 2x, but it's nothing like what you're seeing.

`dhat` gathers a lot of backtraces, I wonder if backtrace gathering on Windows is tragically slow compared to Linux and Mac? I don't have a Windows machine to test on, unfortunately.

**Comment by Eh2406** [comment]
Looks like Julia had a problem with slow backtraces https://github.com/JuliaLang/julia/issues/7759#issuecomment-50415659
as did .NET https://docs.microsoft.com/en-us/troubleshoot/windows-client/application-management/system-diagnostics-stackframe-performance-degrades

I tried adding `-Cforce-frame-pointers=yes` to my rust flags, but it did not help.

**Comment by Eh2406** [comment]
Looking at a profile, and 94% of stacks involve `Backtrace::new_unresolved`. That is consistent with backtrace being slow on Windows.

**Comment by nnethercote** [comment]
Thank you for the data, that's very helpful.

I have added a note to the docs that Windows performance may be much worse: https://github.com/nnethercote/dhat-rs/commit/8fb043a6eb967c80e154d8eb2f62d5d8a9bd7ddd. I don't think there's much else to be done here, so I will close the issue.

**Comment by Eh2406** [comment]
I'm happy to have a profiling tool that **runs** on windows! Documentation seems like a great resolution. Thank you!
