### ISSUE TITLE
How to revue the results on windows

### ISSUE THREAD

**Issue by Eh2406** [nnethercote/dhat-rs#2]
I am a Windows based lifeform, so don't have the pleasure of Valgrind experience. Does the DHAT's viewer work on windows? I could not figure that out from the Valgrind website. How would I get it set up?

**Comment by Eh2406** [comment]
Yes, It works! Clone the Valgrind repo. DO NOT try to build Valgrind. Open the `dhat/dh_view.html`, and it just works.

**Comment by nnethercote** [comment]
[7d7ff17](https://github.com/nnethercote/dhat-rs/commit/7d7ff1707b400b8babcb1606c2b0b914e3014f38) clarifies the instructions.
