### ISSUE TITLE
Unnecessary files in 0.3.2 source

### ISSUE THREAD

**Issue by YgorSouza** [nnethercote/dhat-rs#30]
It seems that some build artifacts and logs were present in the local repo that was published to crates.io, and so they ended up in the crate source distribution: <https://docs.rs/crate/dhat/0.3.2/source/>. This made the crate size go from 31KB in version 0.3.1 to 183KB in version 0.3.2, despite the fact that the only difference between the two is a dependency change.

**Comment by nnethercote** [comment]
Thanks for the report, and apologies for the slow response.

I don't know how those files ended up in there when `cargo publish` fails if there are extra files present. Weird.

Anyway, I just published 0.3.3, which [looks better](https://docs.rs/crate/dhat/0.3.3/source/).
