### ISSUE TITLE
Doesnt generate files or writes anything

### ISSUE THREAD

**Issue by TheGP** [nnethercote/dhat-rs#39]
I added the code to Cargo.toml:
```
[profile.release]
debug = 1

[features]
dhat-heap = []    # if you are doing heap profiling
```

Then to main.rs

```
#[tokio::main]
async fn main() -> Result<(), String> {
	#[cfg(feature = "dhat-heap")]
	let _profiler = dhat::Profiler::new_heap();
```
And installed the crate. I don't see neither any output or files from the tool. What did I do wrong?

P.S. I kill the app with Ctrl + C (error: process didn't exit successfully: `target\debug\tool.exe` (exit code: 0xc000013a, STATUS_CONTROL_C_EXIT)

**Comment by GeorgeHahn** [comment]
You also need to update the global allocator. Add something like this to the top of your `main.rs`:

```rust
#[cfg(feature = "dhat-heap")]
#[global_allocator]
static ALLOC: dhat::Alloc = dhat::Alloc;
```

**Comment by nnethercote** [comment]
@GeorgeHahn is correct. Please read the full docs at https://docs.rs/dhat/latest/dhat/.

**Comment by TheGP** [comment]
@GeorgeHahn @nnethercote sorry I missed it. I added it as well of course, in the time of writing my question.
